# Site
title:              黄毅超的博客
bio:                '哎呀妈呀装个X不容易'
description:        "哎呀妈呀装个X不容易"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/me.jpg'
background:         'assets/img/bg1.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             zn_CH
url:                https://hyichao.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  #enable_coderay:   true
  syntax_highlighter: coderay
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
# disqus_shortname:   saicoco

# Social
# if you don't have any of social below, comment the line.
google:
  #plus:            #username
  analytics:        UA-90273204-1
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
# email:　gjj0816@gmail.com
# twitter:            username
# facebook:           username
github-url:         hyichao
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
# instagram:          username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
# steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
